### ISSUE TITLE
Temp offset

### ISSUE THREAD

**Issue by matata86** [atc1441/ATC_MiThermometer#102]
Hi, can I help me plese.
HOw to set offset of temperatur?
I need offset -0.3C. Which value should I set in the input?

**Comment by atc1441** [comment]
Hey it is 0xFD

https://onlinegdb.com/Hk1CJ2gjv

**Comment by matata86** [comment]
I am sorry, but i do not understand.
Which string should I enter in the field so that the temperature is 0.3C lower (-0.3C).
![Snímek obrazovky pořízený 2020-11-29 10-41-19](https://user-images.githubusercontent.com/28623294/100538341-72742c80-322f-11eb-8e0c-bba54c71e899.png)

**Comment by atc1441** [comment]
it should be FAFD
