### ISSUE TITLE
Couldnt verify (-28)

### ISSUE THREAD

**Issue by havrancek** [atc1441/ATC_MiThermometer#107]
hello
i am a noob
i flashed custom firmware, set mi like advertising but when i am trying to reconnect in mi home i always get this error:
1, device connected
2, couldnt verify (-28)
what should i do to be able to connect it back again to be able to use it elsewhere?
(I mean I want to connect mi home to google home and be able to see thermometer data there)

**Comment by atc1441** [comment]
Hey. The custom firmware is not compatible to mi Home.

Its better you flash the stock firmware back
