### ISSUE TITLE
Release Notes 

### ISSUE THREAD

**Issue by soloam** [atc1441/ATC_MiThermometer#110]
Hello, I've seen a lot of new releases in the last days, but no release notes, what are the changes? Can you provide some release notes to them?

Thank you

**Comment by atc1441** [comment]
Hey  there are no real changes except that the Pythonflasher now has zwo way communication thank to @pilatomic https://github.com/atc1441/ATC_MiThermometer/pull/108

And the other releases where just a test for the Github Actions thanks to @skaldo https://github.com/atc1441/ATC_MiThermometer/pull/104
