### ISSUE TITLE
 Xiaomi Miija version 2

### ISSUE THREAD

**Issue by pablopezunizar** [atc1441/ATC_MiThermometer#113]
First of all thanks for the great work here! I love this proyect.

This is v2 of the LYWSD03MMC Xiaomi Miija 2, could this be an issue? The rest of the behaviour seems to be normal/accurate. I would like to report that I compared data of a device flashed with the custom firmware against 3 other devices. I have noticed: 

1. an offset in the humidity data (all fine with temperature) of around 6 percent points below the others
2. and a general delay reacting to a change in temperature/humidity. 

If you think this is relevant for the proyect and it worths the time it could take to debug, let me know to provide any other info that could be helpful or test anything else.

![photo_2020-12-06_21-03-53](https://user-images.githubusercontent.com/72265425/101291099-a8ed1100-3806-11eb-8f1c-d30c216be05d.jpg)

**Comment by atc1441** [comment]
Hey. 
Both "Features" are exactly as they are right now. 
The offset is known and you can set your own offset via the webflasher, the sensor data the custom firmware shows is directly from the sensor without filtering

The sensor data is only meassured every minute to save power.

**Comment by pablopezunizar** [comment]
Makes sense, thank you @atc1441 !
Closing this.
