### ISSUE TITLE
A lite comparison of readings from several temperature and humidity sensors

### ISSUE THREAD

**Issue by deepcoder** [atc1441/ATC_MiThermometer#116]
First, thank you to the folks contributing to this project!

No issues here, just some data.

Thought some of your followers might find something of interest in these graphs. I am still doing some analysis of the data and I do have a couple other sensors that I may add to the tests.

Of the sensors I have tried, the units that yield the finest granularity of reading for both temperature and humidity are the Govee H5052 (no longer available) and H5074. The Xiaomi LYWSD03MMC with custom code is at the same level in it's temperature data, but does not yield the same number of samples for the humidity readings.

This analysis says nothing about the absolute accuracy of any of the readings, it may be possible to extract some relative comparison between sensors.

Anyway, again thanks for the work. Here are the plots.
<img width="1093" alt="sensor-temperature-01" src="https://user-images.githubusercontent.com/1409547/101428004-c8db0e00-38b4-11eb-9530-02e06d9d2dfd.png">

<img width="1081" alt="sensor-humidity-01" src="https://user-images.githubusercontent.com/1409547/101428028-d09ab280-38b4-11eb-80c1-92b727a023e5.png">

**Comment by atc1441** [comment]
Thank you for the overview
