### ISSUE TITLE
Where can I find the stock firmware?

### ISSUE THREAD

**Issue by erniberni** [atc1441/ATC_MiThermometer#117]
I am not sure if I have overlooked anything. The text mentions that I can flash the stock firmware back again. But where can I find the stock firmware? Do I have to read it from the device?

**Comment by atc1441** [comment]
Hey. It is linked in the readme 
https://github.com/atc1441/ATC_MiThermometer#stock-firmware

**Comment by erniberni** [comment]
I had already thought so. Next time I should always read the whole text before asking stupid questions. Sorry and Thank You

**Comment by atc1441** [comment]
No problem :)
