### ISSUE TITLE
New smileys

### ISSUE THREAD

**Issue by ersinpw** [atc1441/ATC_MiThermometer#119]
First of all @atc1441 great work! I managed easily to flash the custom firmware.

I was wondering if it's it possible to create new custom made smileys.

In LCD.c I saw you declared this:
```
void show_smiley(uint8_t state){/*0=off, 1=happy, 2=sad*/
	display_buff[2] &= ~0x07;
	if(state==1)display_buff[2]|=0x05;
	else if(state==2)display_buff[2]|=0x06;
}
```
Where I understand that 0x05 is the happy face and 0x06 is the sad face. Are these smileys hard coded somewhere in the hardware/software?

**Comment by atc1441** [comment]
Hey. The lcd is only a segment display so not changeable
