### ISSUE TITLE
After flashed custom firmware, I cannot detect them with Mi Home App

### ISSUE THREAD

**Issue by rockkoca** [atc1441/ATC_MiThermometer#124]
The ATC worked very well! Thanks a lot!

However, after flashed custom firmware, I cannot detect them with Mi Home App. 

Any solution for this? Or, it is designed to not working with Mi Home App?

Thanks,

**Comment by atc1441** [comment]
Hey. Thanks 

After flashing the Custom Firmware it is not compatible to the mihome App anymore.

If you want to make it completable again you can flash the stock Firmware which is linked in the description.

**Comment by rockkoca** [comment]
Got it.

Thanks!
