### ISSUE TITLE
Advertising is missing the first 4 bytes

### ISSUE THREAD

**Issue by TheNitek** [atc1441/ATC_MiThermometer#13]
I just tried to implement a parser for the native adv. format, but I noticed that the data first 4 bytes seem to be missing. The payload starts with the mac address right away. Firmware version was the latest from this morning.

**Comment by atc1441** [comment]
That is correct  

The other 4 byte are the length of the data an the service uuid. These are parsed on ble level 

https://github.com/atc1441/ATC_MiThermometer#advertising-format-of-the-custom-firmware

Just take the mac as first byte
