### ISSUE TITLE
Temperature precision

### ISSUE THREAD

**Issue by dzek69** [atc1441/ATC_MiThermometer#131]
With stock firmware I was able to get 2 decimals precision (like: 21.78) (after connecting and reading from ebe0ccc17a0a4b0c8a1a6ff2997da3a6) on temperature reads. Idk what was the precision on advertising

On your firmware on advertising precision is 1 decimal (like: 21.8).

Do you plan to increase this precision maybe?

**Comment by m-kozlowski** [comment]
There's no point. With sensor accuracy at 0.2C the only thing you'll be measuring is ADC noise.

**Comment by dzek69** [comment]
Okay, I expected similar answer, but I didn't expect such low accuracy :)
