### ISSUE TITLE
Help: Restore official firmware lywsd03mmc

### ISSUE THREAD

**Issue by 4rsh-010** [atc1441/ATC_MiThermometer#139]
Hi,

Is it possible to restore official firmware? I have now a custom firmware, but i want the official firmware. 

Since the custom firmware, i can not connect on homebridge.

**Comment by atc1441** [comment]
Hey. The stock firmware is linked in the repos readme, you can simply flash it back

**Comment by 4rsh-010** [comment]
Thanks

**Comment by r3ndszergazda** [comment]
Anyone knows the link? It's not in the readme.
