### ISSUE TITLE
Advertising format

### ISSUE THREAD

**Issue by pvvx** [atc1441/ATC_MiThermometer#153]
Mi Advertising formats all data in little-endian.

Customer Advertising format atc1441 is a mixture of little-endian and big-endian:
UUIDs are little-endian and MAC and data are big-endian?

GATT Service 0x181A Environmental Sensing, 
GATT Characteristic and Object Type 0x2A1F (Temperature) and  0x2A6F (Humidity) in little-endian.

How did it happen? :)

**Comment by atc1441** [comment]
The Mi Advertising data was fixed and just copied from the stock. 

On the atc1441 one the different data entry came peace by peace so it is maybe mixed up 

The Enviromental data was tested with nRFConnect to be detected and then used like it worked

Thank you Victor for all your effort ! :)
