### ISSUE TITLE
Cant flash, ativate and send parameters to custom firmware till 09/09/2020

### ISSUE THREAD

**Issue by cheese202** [atc1441/ATC_MiThermometer#16]
Today i can't do activation (stuck) of stock firmware device, can't flash stock and custom firmware devices (even reflashed yesterday) and can't send parameters to custom firmware. Also i CAN connect to device.

![Снимок экрана 2020-09-09 в 10 55 03](https://user-images.githubusercontent.com/35533614/92570967-331aed00-f28b-11ea-89b2-4f5e141359db.png)

![Снимок экрана 2020-09-09 в 10 56 47](https://user-images.githubusercontent.com/35533614/92571096-5cd41400-f28b-11ea-941c-0ce78a28c9dc.png)

Yesterday everything was fine. But till today t seems that something broken in script. 

Tried on 3 devices and on MAC, PC and Android 10 pixel 4. Nothing.

Screenshots attached below.

Any ideas what happening? 

Before today everything worked fine.

**Comment by atc1441** [comment]
Hey, yes that was caused by the merge. 

reversed it now as something was broken with that one, works now again :)
