### ISSUE TITLE
Humidity reading error

### ISSUE THREAD

**Issue by D-moe** [atc1441/ATC_MiThermometer#161]
After flashing the custom firmware all my sensors oscillate between the actual humidity reading and the number 99. I did not notice this issue with the stock firmware so I’m led to believe it is some sort of software bug. I was using the parameters Fahrenheit and 10 minute interval as the changes from default.

**Comment by KoalaBear84** [comment]
See: https://github.com/atc1441/ATC_MiThermometer#show-battery-level-in-lcd-

It's the battery level. You can disable it with the flasher.

**Comment by D-moe** [comment]
Awesome thanks for the heads up, I'll give that a shot.

**Comment by D-moe** [comment]
Great, problem resolved, appreciate it @KoalaBear84
