### ISSUE TITLE
Offset in my own Custom Firmware

### ISSUE THREAD

**Issue by Bibo1984** [atc1441/ATC_MiThermometer#167]
Hello

i'hd build my own Firmware with some Custom Settings an it works perfect.
Now i've tryed to enter a Offset for each of them....
But it not works, wich format i've to use that it works correctly?

I tryed: humi_offset = 10;
![atc](https://user-images.githubusercontent.com/71224792/106634266-ead4d200-657f-11eb-810b-a178f0e41082.png)

thanks for your help!

**Comment by atc1441** [comment]
Hey, 

the temp_offset can range from -12,6 to 12,5 °C and will add or subtract 0,1°C for each number
the humi_offset can range from -50 to 50 and will add or subtract one percent for each number

hope that this helps

**Comment by Bibo1984** [comment]
@atc1441 
Thanks for the fast help! I've found the mistake the problem was not the parameters in the firmware.
The Telink flasher doesn't upload the bin file again till i close and reopen it again.
It works now very fine. Thanks for your great work!

**Comment by atc1441** [comment]
Thank you for the feedback :)
