### ISSUE TITLE
USB-UART connection pinout

### ISSUE THREAD

**Issue by lknop** [atc1441/ATC_MiThermometer#169]
I am not sure if it is just me but I am not sure if I am getting this right. Looking at the pinout image I am a bit puzzled:

![pinout](https://raw.githubusercontent.com/atc1441/ATC_MiThermometer/master/Mi_SWS_Connection.jpg)

Should I join USB-UART RXD pin with TXD pin with 1k resistor and connect them both to P14 ? Or is something missing from the picture? No other pins such as reset are necessary?

Should the USB-UART adapter's IO Vcc be 3.3V only or can it be a 5V one?

Thanks in advance for clarification.

**Comment by atc1441** [comment]
You are right with your assumption.
See this one:
https://youtu.be/mt-9jcCwmFA

Only 3.3V will work

**Comment by lknop** [comment]
Thank you!
