### ISSUE TITLE
Compatibility with 2020 version of the thermometer?

### ISSUE THREAD

**Issue by skibbipl** [atc1441/ATC_MiThermometer#178]
I would like to order few more thermometers from aliexpress, but from what I can see, sellers are advertising them as 2020 version. Are there any differences between old version and 2020 one? Is this new version compatible with this firmware?

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/110846169-86164100-82bc-11eb-98b8-85e55566e728.png)
Identical

**Comment by gitkobold** [comment]
Hi.
Are lywds03 and mhoc401 use telink (and supported by the page)?
There are lots of other sensors and would be good to flash original fw at least..
Thanks

**Comment by skibbipl** [comment]
@pvvx thanks for confirmation. Ordered 20 ;)
