### ISSUE TITLE
LYWSD02 Stock Firmware

### ISSUE THREAD

**Issue by MappleStore** [atc1441/ATC_MiThermometer#182]
Hello, I use a LYWSD02 (with e-ink display). Since the last update to official firmware 1.1.2_0087 via the Xiaomi Home app, the unit shows random segments on the display (see attached photo). Maybe the firmware update was faulty. Is there a way to restore the firmware with your tool (maybe in the future)?
![Image1](https://user-images.githubusercontent.com/10231799/113478705-d4b59600-948a-11eb-9758-d34a5e05cbc1.jpg)

**Comment by pvvx** [comment]
[LYWSD02](https://pvvx.github.io/LYWSD02/) has a different chip and there are no alternative firmware versions for it yet.

**Comment by MappleStore** [comment]
Ok, thank you.
