### ISSUE TITLE
Publish every 30 seconds in stead of 5 mintues

### ISSUE THREAD

**Issue by sybux** [atc1441/ATC_MiThermometer#186]
Hi there,

I've flashed successfully my thermometer, I was able to change some settings as disable battery display, and normal send every 5 minutes, but in my ESPHome logs, I can see that all my sensor are flushing data every 30 seconds.

I've just made the turn of my device to reset this value to 5 minutes, but no change. Is there a way to be sure that settings is set ?

Thx for help

**Comment by atc1441** [comment]
Hey. Please try out victors version of this firmware. There the setting is simpler. And it is much more evolved, it is linked in the readme.md

In general the devices do send out notifications all the time and only change on new advertising time

**Comment by sybux** [comment]
Sorry for late answer.... it's working like a charm ! thx
