### ISSUE TITLE
Advertising interval not honored

### ISSUE THREAD

**Issue by fitch** [atc1441/ATC_MiThermometer#19]
At first, thanks for amazing work on this flasher & custom firmware! :)

I have 6 devices flashed with the newest https://github.com/atc1441/ATC_MiThermometer/blob/master/ATC_Thermometer.bin. It seems that despite specifying the advertising interval to 1 minutes, I seem to be getting advertisements quite often (every 1-20 seconds). Is there something I'm missing?

**Comment by atc1441** [comment]
Hi, 

currently the advertising is limited to 3 minutes maximum but should work for 1 minute fine. 

also it does notify when a change greater than 0.5°C or 5% data is happening then it does notify instantly, you can change that behavior with the web flasher.

**Comment by soloam** [comment]
Hello @atc1441  so setting to 10s does not work correct? I also tried to set FC01 to notify at 0.1ºC change, but does not seems to work!

Tks

**Comment by atc1441** [comment]
Hey. Both thinks should work fine

**Comment by soloam** [comment]
I'm using esphome to grab the changes. I do it with "Mi Like", the 10s passes and no update, also I blow hot air to the sensor, I see the value changing in the lcd, but no report.

Thank You

**Comment by atc1441** [comment]
It is possible that esphome has it blocking for faster updates?!

**Comment by nikito7** [comment]
mmc only advertises every 10min but multiple times shortly

try with platform xiaomi_cgg1

**Comment by kktmp1** [comment]
> Hi,
> 
> currently the advertising is limited to 3 minutes maximum but should work for 1 minute fine.
> 
> also it does notify when a change greater than 0.5°C or 5% data is happening then it does notify instantly, you can change that behavior with the web flasher.

@atc1441 It is possible to increase the Advertising interval above 3 minutes. The battery is draining fast. Using the FEFF command wouldn't be useful, would it?

Thanks for your amazing work !!

**Comment by atc1441** [comment]
The battery should not drain faster, it is doing the same thing even with short interval. 

in general the battery is shown lower as it is as 100% is 3.1V and not 3.0V in my firmware to see how much overhand there is

**Comment by kktmp1** [comment]
Ok thanks @atc1441  I'll keep an eye on it

Of 8 sensors, an average value of 80% in two weeks. It may be the expected normal battery discharge.
