### ISSUE TITLE
Bricked? Sad face / Battery indication shows with high humidity. 

### ISSUE THREAD

**Issue by Skyridr** [atc1441/ATC_MiThermometer#191]
So I've flashed this on my LYWSD03MMC, but after flashing I am no longer able to connect to the bluetooth device, and its showing a sad face with a battery icon at the bottom every 5 seconds orso that also changes the humidity from around 40% to around 90, and then goes back to normal again.. and loop.

Did I brick it?

**Comment by Skyridr** [comment]
Fixed it ^^.

**Comment by mdesign83** [comment]
What was the fix?
