### ISSUE TITLE
Possible to turn of display?

### ISSUE THREAD

**Issue by alexw1982** [atc1441/ATC_MiThermometer#197]
Me (and I assume a lot of other people) utilize the unit mainly as a sensor with little use for the display in many cases. Would it be technically possible to turn of the screen to increase battery life? this would be awesome....

**Comment by atc1441** [comment]
Hey,

the battery life does not increase by turning it of. 

The main power draw is the sensor reading.

i can not suggest on doing it

**Comment by alexw1982** [comment]
Ok - thanks anyway :-)

**Comment by dgoadby** [comment]
If you really want the display off then you could hack the PCB and cut the VCC to the display. The LCD draw is minimal and, if you did kill the LCD power supply, you would lose the only obvious indication that it is working.

**Comment by alexw1982** [comment]
> 
> 
> If you really want the display off then you could hack the PCB and cut the VCC to the display. The LCD draw is minimal and, if you did kill the LCD power supply, you would lose the only obvious indication that it is working.

Fully agree - it would have only made sense if there was a significant power saving benefit...
