### ISSUE TITLE
bluetooth is missing

### ISSUE THREAD

**Issue by LoreYun** [atc1441/ATC_MiThermometer#199]
Hi,
I use this page (https://atc1441.github.io/TelinkFlasher.html) and upload firmware(Release 38) to my LYWSD03MMC(Date of production is 2021.04). 
After flashing, device lose the bluetooth icon, and can not found from any device.

**Comment by atc1441** [comment]
Can you try removing the battery?

If that doesnt help you may want to reflash it via a UART converter

**Comment by LoreYun** [comment]
> Can you try removing the battery?
> 
> If that doesnt help you may want to reflash it via a UART converter

Thanks,
I have tried is before, but still no bluetooth right now.
