### ISSUE TITLE
[Random question] What is the app you use to see BLE details on your phone?

### ISSUE THREAD

**Issue by jnpwly** [atc1441/ATC_MiThermometer#20]
Kia ora, Aaron, from NZ 👋

Just a random question, which is not specifically related to this code (for which, _**many**_ thanks!). What is the app you use on your phone for seeing the BLE details? I couldn't work it out from your video, but it looks really useful.

Cheers!
   Jon

**Comment by RadicalGR1** [comment]
I think it's the nRF Connect.
