### ISSUE TITLE
Using webtool to get CGPR1 bindkey results in "Not connected"

### ISSUE THREAD

**Issue by Timmiej93** [atc1441/ATC_MiThermometer#212]
I'm trying to get the bindkey for the CGPR1 motion detector. I can connect to it just fine, but when I click "do activation", it always says "Not connected", even if it says "Connected" right above that. I have tried using my PC and my phone, which both have flashed LYWSD03MMC thermometers without issue.
I checked, the CGPR1 does have a Telink TLSR82** MCU (TLSR8253 IIRC), so I guess something else is causing the issue? Any help would be greatly appreciated.

**Comment by unrelentingtech** [comment]
Similar problem with the RTCGQ02LM "motion sensor 2", I managed to activate one of them using a silly modification to the script, but another identical one did not work:

https://github.com/atc1441/atc1441.github.io/issues/10#issuecomment-927138149

**Comment by pvvx** [comment]
> I checked, the CGPR1 does have a Telink TLSR82** MCU (TLSR8253 IIRC), so I guess something else is causing the issue?

plastic lever - associated with the pairing button. To switch to this mode, press and hold the button for about three seconds until the blue LED blinks ?

**Comment by jturn08** [comment]
I had the same problem of not being able to get bindkey using Telink Flasher, and was able to successfully get the bindkey using exact steps below.

1. Used `[Telink Flasher v3.3](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html)`
2. Open the back cover of the sensor and press the blue plastic lever button for about 3 seconds until blue LED starts blinking. Release the blue pairing button.
3. In Telink Flasher v3.3 webpage, select "Connect" button and then select "Qingping Motion & Light" device
4. Select "Do activation" button.

After a few tries, I was able to get the token and bindkey.

**Comment by Timmiej93** [comment]
I did eventually manage to get one of my two CGPR1's working, but it took way too many tries, probably over 20. Anyway, that's an issue with the actual product, not with the software.

**Comment by pvvx** [comment]
What's the point of registering with mijia if CGPR1 transmits all data and events in advertising packages via the unprotected Qingping protocol?
https://pvvx.github.io/CGPR1/

**Comment by Timmiej93** [comment]
So you'd only need the MAC address in order to listen to the messages send by the CGPR1?

**Comment by pvvx** [comment]
> So you'd only need the MAC address in order to listen to the messages send by the CGPR1?

Requires a sniffer or BLE Advertising receiver.

**Comment by pvvx** [comment]
> I had the same problem of not being able to get bindkey using Telink Flasher, and was able to successfully get the bindkey using exact steps below.
> 
> 1. Used [Telink Flasher v3.3](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html)
> 2. Open the back cover of the sensor and press the blue plastic lever button for about 3 seconds until blue LED starts blinking. Release the blue pairing button.
> 3. In Telink Flasher v3.3 webpage, select "Connect" button and then select "Qingping Motion & Light" device
> 4. Select "Do activation" button.
> 
> After a few tries, I was able to get the token and bindkey.

CGPR1 out of the box is in the original unencrypted Qingping BLE ad format. In this mode, light and battery level are transmitted every second. And all events are sent in unprotected Qingping format. OTA works without bindkeys.
Switching to Qingping BLE mode and decoupling from Mi-Home is carried out by pressing the button for a very long time until the LED stops blinking.

**Comment by jturn08** [comment]
> CGPR1 out of the box is in the original unencrypted Qingping BLE ad format. In this mode, light and battery level are transmitted every second. And all events are sent in unprotected Qingping format. OTA works without bindkeys. Switching to Qingping BLE mode and decoupling from Mi-Home is carried out by pressing the button for a very long time until the LED stops blinking.

How do you configure the CGPR1 in esphome? If I leave out bindkey, then I get an error `bindkey is a required option for binary_sensor.xiaomi_cgpr1`. I also get an error if I include empty string as bindkey.

**Comment by pvvx** [comment]
> How do you configure the CGPR1 in esphome without including a bindkey? If I leave out bindkey, then I get an error `bindkey is a required option for binary_sensor.xiaomi_cgpr1`. I also get an error if I include empty string as bindkey.

[CGPR1_Utils.html](https://pvvx.github.io/CGPR1/CGPR1_Utils.html)

https://pvvx.github.io/CGPR1/

**Comment by jturn08** [comment]
Yes, I was able to get CGPR1 bindkey using your utils.

Is there a way to configure CGPR1 in esphome while CGPR1 is set to the original unencrypted Qingping BLE ad format? Or is getting bindkey the only way to use CGPR1 in esphome right now?

**Comment by pvvx** [comment]
ESPHome does not support Qingping format.

**Comment by almirus** [comment]
@pvvx hi! here you wrote https://github.com/atc1441/ATC_MiThermometer/issues/212#issuecomment-968629758
it's work, device switch to Qingping mode, but how to switch pairing mode simultaneously?
i want to add to HA via [qingping integration](https://www.home-assistant.io/integrations/qingping/), no one device was found, however, here https://pvvx.github.io/CGPR1/CGPR1_Utils.html I've get all indicators

**Comment by pvvx** [comment]
Home Assistant 2023.5.2

Bluetooth integration
![image](https://user-images.githubusercontent.com/12629515/236670043-2827b609-bc23-4cca-b9f6-8e2b2fb6b820.png)
Qingping integration
![image](https://user-images.githubusercontent.com/12629515/236669634-49b6d048-196b-4caa-9fb4-fe50306674c6.png)
![image](https://user-images.githubusercontent.com/12629515/236669828-ec377718-663b-452a-ae70-1a1841c4f8fe.png)
Bluetooth integration does not work with all BLE variants.
Write to the authors of Bluetooth integration. Bluetooth integration does not accept BLE advertisements subject to Bluetooth SIG standards.
---

Passive BLE Monitor integration
![image](https://user-images.githubusercontent.com/12629515/236669973-64bc877a-7f32-4d95-877b-0e9ef12f95ca.png)
![image](https://user-images.githubusercontent.com/12629515/236669881-8e27d50d-cf61-4c82-97e0-f1617ec1b0a1.png)

**Comment by pvvx** [comment]
Bluetooth integration and its associated APIs do not work correctly with "passive scanning".
![image](https://user-images.githubusercontent.com/12629515/236671255-f3605c89-b1fb-4809-ad70-8e997c1f5f1b.png)
And in active scanning mode, all BLE devices are constantly being requested, draining the batteries and Bluez is constantly writing to disk, killing the SSD (TBW).
