### ISSUE TITLE
LYWSD03MMC - after flash all segment are on display

### ISSUE THREAD

**Issue by DastyDiesel** [atc1441/ATC_MiThermometer#222]
Hello,
I did flash of my LYWSD03MMC using website. After it the display was freezed. I removed battery for a couple of minutes and after starting the display lights completely (it means each segment is visible). I can still connect to device via website for flashing but I need also values on display. Do you have any idea what is wrong?
Thank you.

**Comment by ChefkeGremmen** [comment]
I have the exact same issue, already 'bricked' 2 devices.
