### ISSUE TITLE
Adjust Smiley Status Values

### ISSUE THREAD

**Issue by spooknik** [atc1441/ATC_MiThermometer#235]
Hello, thanks for the awesome project! 

Do you think it's possible to adjust the variables which control the smiley status? 

i.e. In the stock firmware it is smiley between 20% and 85% RH. But is it possible to adjust this value to say 10% - 30%. 

This would be useful for situations where you need to custom solutions for humidity and temperate. Like 3D filament drying boxes.

**Comment by atc1441** [comment]
Hey. Sure its all open source :)

**Comment by spooknik** [comment]
Thanks, I will attempt to dive in ☺️

**Comment by atc1441** [comment]
Its something in those lines:

https://github.com/atc1441/ATC_MiThermometer/blob/master/ATC_Thermometer/app.c#L33

Also the array above it

**Comment by spooknik** [comment]
Thank you 👍
