### ISSUE TITLE
Feature, dump original firmware with OTA flasher tool

### ISSUE THREAD

**Issue by ModuloFS** [atc1441/ATC_MiThermometer#246]
Hello,

would it be possible to add the functionality of reading the original firmware from the LYWSD03MMC sensor with the OTA flash tool: https://atc1441.github.io/TelinkFlasher.html ?

**Comment by atc1441** [comment]
Hey. That is unfortunately not possible

**Comment by ModuloFS** [comment]
Thats not good to hear. But thank you anyway for your answer your work on this software!! I think this tool should do the job then: https://github.com/pvvx/TlsrComSwireWriter ?

**Comment by atc1441** [comment]
Thanks as well.

Yes that tool can be used to dump the flash
