### ISSUE TITLE
[FR] Command line OTA flasher

### ISSUE THREAD

**Issue by m-kozlowski** [atc1441/ATC_MiThermometer#27]
Any chance for command line implementation of OTA flasher?
I'd love to see that happen, as I'm currently running your firmware on 12 devices (another 8 are on the way;) and updating that swarm using web flasher is serious pain in the ass;)
Command line version would allow much more flexibility (automation).

**Comment by atc1441** [comment]
There is the beginning of the not working activation script. 

That could be completed to also flash the devices.

But its not a thing i will do, it was hard enough to get the script itself running and the crypto solved :)
