### ISSUE TITLE
JBL device shows up even when "Hide unsupported"

### ISSUE THREAD

**Issue by Zixim** [atc1441/ATC_MiThermometer#30]
![image](https://user-images.githubusercontent.com/7814664/95188552-de588c80-07cc-11eb-82f8-966e46db06b4.png)
This doesn't feel like expected behaviour.

**Comment by atc1441** [comment]
That is the expected behaiviour :)

It will only hide the one that does not have a name or where only the mac is shown, it does not filter for compatibility

**Comment by Zixim** [comment]
I see what you mean... then `Hide unsupported` is the wrong label.
Because JBL speakers are certainly unsupported but they are not hidden.

`Hide unknown`  ?

**Comment by atc1441** [comment]
Will change it :)
