### ISSUE TITLE
"Advertising interval" term is missused?

### ISSUE THREAD

**Issue by bam80** [atc1441/ATC_MiThermometer#309]
The BLE "Advertising interval" term meaning is seems quite different than it's used in the Readme here: 
https://github.com/pvvx/ATC_MiThermometer/issues/450#issuecomment-1868541880

Could you clarify that?

**Comment by atc1441** [comment]
It is the new Measurement interval 👍

**Comment by bam80** [comment]
OK, thank you. Do you think we could fix the Readme then?

**Comment by atc1441** [comment]
Did just that :) 

Have a nice Christmas !

**Comment by bam80** [comment]
You too, thanks! :)
