### ISSUE TITLE
Setup local https://atc1441.github.io/TelinkFlasher.html

### ISSUE THREAD

**Issue by orrpan** [atc1441/ATC_MiThermometer#31]
Hi, is it possible to run a local hosted version of https://atc1441.github.io/TelinkFlasher.html ?
Tried with python simple server, and that did not work.

**Comment by atc1441** [comment]
You can simply save the html file and open it. That it

**Comment by orrpan** [comment]
> You can simply save the html file and open it. That it

Ahh, chrome didn't like me using the ip:port, but localhost:port worked. Guess it restricts BT at like unsecured connections (which the ip is)

**Comment by atc1441** [comment]
Yes it needs https

But as mentioned you would not even need to run a server just open the file and it will work without https
