### ISSUE TITLE
Problem activating LYWSD03MMC v2.1.1_0159

### ISSUE THREAD

**Issue by jjmuriel** [atc1441/ATC_MiThermometer#315]
Hi,

I can't set the new Bind Key for LYWSD03MMC sensor.  I'm stucked on activation:

17:52:45: Searching for devices
17:52:49: Connecting to: LYWSD03MMC
17:53:02: Detected Mi Thermometer
17:53:02: Connected
17:53:19: Activating now, please wait...

Chrome Developer Console logs:

TelinkFlasher.html:86 {optionalServices: Array(4), acceptAllDevices: true}
TelinkFlasher.html:429 Found GATT server
TelinkFlasher.html:429 Found service
TelinkFlasher.html:429 Found write characteristic
TelinkFlasher.html:351 Services: 0000fe95-0000-1000-8000-00805f9b34fb
TelinkFlasher.html:351 Services: ebe0ccb0-7a0a-4b0c-8a1a-6ff2997da3a6
TelinkFlasher.html:351 Services: 00010203-0405-0607-0809-0a0b0c0d1912
TelinkFlasher.html:429 Status: Detected Mi Thermometer
TelinkFlasher.html:429 Found Main service
TelinkFlasher.html:429 Found Write characteristic Speed
TelinkFlasher.html:429 Found Temp characteristic
TelinkFlasher.html:429 Found Main service
TelinkFlasher.html:429 Found enc_10 char
TelinkFlasher.html:429 Found enc_19 char
TelinkFlasher.html:429 Status: Connected, you can now Do the Activation to either get the Token or flash a new Firmware
TelinkFlasher.html:429 Temp/Humi: 31.25°C / 49%
TelinkFlasher.html:429 Send: a2000000
TelinkFlasher.html:429 Enc_19: 000000000200
TelinkFlasher.html:429 Send: 00000101
TelinkFlasher.html:429 Enc_19: 01000200000000626c742e322e31653461647435
TelinkFlasher.html:429 Enc_19: 02006f676f6b3030
TelinkFlasher.html:429 Send: 00000100
TelinkFlasher.html:429 Send: 15000000
TelinkFlasher.html:429 Send: 000000030400
TelinkFlasher.html:429 Enc_19: 00000101
TelinkFlasher.html:429 Send: 01008a2342ef0f65a8474744561cb619ee500a8d
TelinkFlasher.html:429 Send: 02003db9a4bea77139b36bed8bee73a4254207dc
TelinkFlasher.html:429 Send: 0300b871e4f5384af97c770775a48ea0e4d78ee1
TelinkFlasher.html:429 Send: 04001c5d5d34c8bd2eb04617
TelinkFlasher.html:429 Enc_19: 00000100
TelinkFlasher.html:429 Enc_19: 000000030400
TelinkFlasher.html:429 Send: 00000101
TelinkFlasher.html:429 Enc_19: 01003ab1d08b4e7be0ce0c1f77ce134aa4f58c2f
TelinkFlasher.html:429 Enc_19: 02004c6d880aaee618ca0aca573c2f67ae01be31
TelinkFlasher.html:429 Enc_19: 03004ab13d370f1ce1ce78f0429956a67c4d160b
TelinkFlasher.html:429 Enc_19: 0400db8aaf14c1a5697ea27e
TelinkFlasher.html:429 Send: 00000100
TelinkFlasher.html:429 Send: 000000000200

What can I do?

Thanks

**Comment by AstashovAndrey** [comment]
please read all issues before asking
https://github.com/atc1441/ATC_MiThermometer/issues/298
