### ISSUE TITLE
lywsd03mmc not flashing with new firmware

### ISSUE THREAD

**Issue by muaddiib** [atc1441/ATC_MiThermometer#318]
Some days ago lywsd03mmc B1.5 updated to 2.1.1_0159 firmware from Xiaomi and Telink Flasher not work anymore. In logs it always require Activation.

> 08:38:01: Not connected
> 08:38:03: Searching for devices
> 08:38:39: Connecting to: LYWSD03MMC
> 08:38:46: Detected Mi Thermometer
> 08:38:47: Connected
> 08:39:05: Activating now, please wait...
> 08:41:43: Error on sending setting FB00
> 08:41:50: Error on sending setting FB00
> 08:42:16: Error on sending setting 0C
> 09:31:50: File was selected, size: 64320 bytes
> 09:31:50: Count: 4020
> 09:31:51: Disconnected.
> 09:31:51: Searching for devices
> 09:32:01: Connecting to: LYWSD03MMC
> 09:32:04: Not connected
> 09:32:07: Detected Mi Thermometer
> 09:32:07: Connected
> 09:32:07: Activating now, please wait...
> 09:32:12: Start DFU
> 09:32:12: Please do the Activation first
> 10:03:35: Disconnected.

**Comment by dbarwikowski** [comment]
#298
