### ISSUE TITLE
Random MAC address assigned to my device

### ISSUE THREAD

**Issue by richard-scott** [atc1441/ATC_MiThermometer#330]
After flashing ATC firmware, Google Chrome gives each device a random Mac address and removes BLE name which includes the last three bytes of the MAC Address. This makes it really really hard to find the device you are after.

<img width="453" alt="Screenshot 2024-07-25 at 15 13 15" src="https://github.com/user-attachments/assets/f46254a7-8695-44c6-8b38-0a815cfcd7db">

**Comment by atc1441** [comment]
Each device will show its mac on boot so you can identify them 🙂

**Comment by richard-scott** [comment]
Yeah, it does. And those are different to this list.

**Comment by atc1441** [comment]
Ah I understand.
Other way would be to turn all unwanted of or look for the BLE Logo appearing the one you are connected to

**Comment by richard-scott** [comment]
Yes, I have been doing that, so that is why I reported the bug, as the two do not match up.

Here is the list of my device's real Mac addresses:

```
A4:C1:38:CC:D7:30
A4:C1:38:F4:1A:41
A4:C1:38:3C:EB:4B
A4:C1:38:14:54:EC
A4:C1:38:4C:EF:E8
```

As you can see, these all start with A4:C1:38 as expected.

**Comment by atc1441** [comment]
We can not do much about it sadly, google is showing random macs for (stupid) security reasons to stop tracking and such

**Comment by atc1441** [comment]
The firmware could get one more CMD like "GetMac" where it will respond itd MAC to as a solution but its a rare case of problem these days

**Comment by richard-scott** [comment]
Is there any way to update the 'ATC' text part of what I see to extend that to include the last three bytes of the MAC Address? That would help lots?

**Comment by richard-scott** [comment]
> The firmware could get one more CMD like "GetMac" where it will respond itd MAC to as a solution but its a rare case of problem these days

So, if you have 100 devices in your setup, how do you easily identify them?

**Comment by atc1441** [comment]
The Name does include the last 3 bytes of the mac, but Google is removing them as well as the Mac and only shows random macs.

The mac on the device is not random it is Google/The browser showing a random mac


As mentioned it is not the fault of the firmware it is the brwoser that got this annoying feature added over the years

**Comment by richard-scott** [comment]
I've found a solution.... and it's interesting that Victor's firmware seems able to do it.

<img width="453" alt="Screenshot 2024-07-25 at 16 54 17" src="https://github.com/user-attachments/assets/11157fd8-dcc0-4f27-b0fc-5a8fc879b208">

**Comment by atc1441** [comment]
Peefect :)
