### ISSUE TITLE
Humidity unstable (jumps 30, 60, 30, 60...) with this firmware

### ISSUE THREAD

**Issue by andrey-utkin** [atc1441/ATC_MiThermometer#334]
I flashed my LYWSD03MMC with Release 79.

Temperature indication on screen is reasonable, but humidity on screen jumps around every 10 seconds: 30-something, 60-something, 30-something, 60-something, and so it goes.

This doesn't seem to change with settings available on your web flasher.

Flasing original firmware Original_OTA_Xiaomi_LYWSD03MMC_v1.0.0_0130.bin from pvvx restores the normal behaviour.

BTW @atc1441 could you please share the original firmware dumps you yourself dumped?

**Comment by atc1441** [comment]
The jumping is the battery percentage, every time the battery icon is shown the humi nimber is the battery :)

**Comment by andrey-utkin** [comment]
Ah! Thanks :)
