### ISSUE TITLE
Temp/Humi: waiting for data

### ISSUE THREAD

**Issue by txq92** [atc1441/ATC_MiThermometer#36]
I has flash device , but when connect then not display Temp/Humi
![Screenshot_2020-10-10-23-06-23-615_com android chrome](https://user-images.githubusercontent.com/56432960/95659841-16a1f700-0b4e-11eb-9f3e-45af1be9629f.png)

**Comment by atc1441** [comment]
That is only activated for the stock rom. 

It will not be displayed there. If the log page says custom firmware detected than its all good
