### ISSUE TITLE
Make 0xAF = Mi Like default

### ISSUE THREAD

**Issue by kiwipaulrob** [atc1441/ATC_MiThermometer#37]
I am setting these sensors up in home assistant using the blue HACS add in. It expects the sensors to broadcast using the Mi Like format. I can change the sensors to transmit using the Mi Like format but this will reset to the custom format when I change the battery. Can you consider making the Mi Like format the default? Thank you for your excellent work.

**Comment by atc1441** [comment]
Hey. 

I will not do that.

You can compile either your own firmware or in future i want to make the settings persistense but that will take time

**Comment by kiwipaulrob** [comment]
I understand and that is reasonable. Could you possibly generate a bin with Mi Like as the default?

**Comment by michapr** [comment]
I compiled for you:
https://smarthome-work.com/download/ATC_Thermometer_MiDefault.bin
Take it for your own risk - I will remove it soon because will not be updated if any changes in app.
Hope it will help.
@atc1441 - I hope you agree with it.

**Comment by kiwipaulrob** [comment]
Thank you that is very kind. Best wishes.

**Comment by juhjar** [comment]
> I compiled for you:
> https://smarthome-work.com/download/ATC_Thermometer_MiDefault.bin
> Take it for your own risk - I will remove it soon because will not be updated if any changes in app.
> Hope it will help.
> @atc1441 - I hope you agree with it.

Cool, as you have build environment setup, could you build following: MiLike, no smiley, battery level disabled, 5min interval.
Thank You...

**Comment by michapr** [comment]
Hi,
@juhjar - here is your version ;)
https://smarthome-work.com/download/ATC_Thermometer_MiDefault_noSmiley_150s.bin

Because of this I have used 150 seconds advertising interval:
https://github.com/atc1441/ATC_MiThermometer/issues/33

**Comment by Soni93200** [comment]
> Hi,
> @juhjar - here is your version ;)
> https://smarthome-work.com/download/ATC_Thermometer_MiDefault_noSmiley_150s.bin
> 
> Because of this I have used 150 seconds advertising interval:
> #33

Thanks for this, solved my problem, sensor was not detected with original custom firmware :p

**Comment by benek984** [comment]
@michapr If this is too much just ignore but could you compile for me as fallow: Smile: Comfort indicator, MiLike, Battery: Disabled, Advertise: 10 seconds.

Thank you in advance.

**Comment by atc1441** [comment]
We definitely need an online compiler for this :D

**Comment by TheNitek** [comment]
Or persistent settings storage ;-)

**Comment by atc1441** [comment]
Yeah that would solve a lot as well maybe ^^

**Comment by michapr** [comment]
@benek984 - your version ;)
https://smarthome-work.com/download/ATC_Thermometer__benek984.bin

**Comment by attley86** [comment]
Issue was closed  #33 but I would appreciate if someone could compile a binary for me that has: MiLike, no smiley, battery level disabled, 5min interval. Cheers.
