### ISSUE TITLE
accidently flashed the zip, not the bin

### ISSUE THREAD

**Issue by gbomacfly** [atc1441/ATC_MiThermometer#38]
Hi there,

thanks for this tool. But I made a mistake. I flashed the zip-file, not the extracted bin.
I'm trying to flash through UART through a USB-Adapter. It seems to write and finish, but the device is still dead.
I've tried with RX and TX, but both with no luck. Also the stock- and your .bin
Some other ideas?

**Comment by atc1441** [comment]
If you are on mac please try it with a windows mashine. Flashing works bettere there

**Comment by atc1441** [comment]
Added a real file check to the webflasher so its only possible to select a real firmware file for telink.

This does not help you but in the future

**Comment by gbomacfly** [comment]
> If you are on mac please try it with a windows mashine. Flashing works bettere there

Thanks a lot, this had worked fine :)
And also thanks for the filecheck :)
