### ISSUE TITLE
Web Flasher: device.watchAdvertisements is not a function

### ISSUE THREAD

**Issue by elazarrosenthal** [atc1441/ATC_MiThermometer#41]
Web flasher shows 
In log:

Searching for devices
06:49:47: TypeError: device.watchAdvertisements is not a function

**Comment by elazarrosenthal** [comment]
Just wondering is there missing functionality 
or is this an unneeded function anyway

**Comment by atc1441** [comment]
That is an relict os some testing i did. You can ignore it

**Comment by elazarrosenthal** [comment]
Thanks I had been trying to understand the code in the webpage 
and was wondering if somthing useful was missing.

I know it worked I had flashed a thermometer with an the older version
