### ISSUE TITLE
Measure battery more seldom

### ISSUE THREAD

**Issue by orrpan** [atc1441/ATC_MiThermometer#43]
As I understand measuring the battery is the thing that drains it the most, is it possible to only do these measurements like once a day or at least once a hour?

**Comment by atc1441** [comment]
Hey.  that would be my plan to do but right now nothing can be more than 2-3 minutes apart because of the overflow Bug in the future there will be real working millis counter

**Comment by tshcherban** [comment]
As far as i can see from sources, currently battery is measured once per 5 minutes
![image](https://user-images.githubusercontent.com/13539236/96251851-bda4e980-0fb9-11eb-8125-a62db2193713.png)
@orrpan, have you tried to adjust `Read battery delay`? I've successfully changed it to 15 minutes.
@atc1441 where the overflow bug is happening? Can you provide a bit more details?

**Comment by TheNitek** [comment]
Wouldn't it be possible to disable battery measurements completely? Personaly I don't care about the value, if the device is dead I'll just replace the battery, but I like the idea replacing the battery more seldom ;-)

**Comment by atc1441** [comment]
Thats a good argument!

It can be simply disabled by removing the battery part in the app main loop
