### ISSUE TITLE
INK screen devices support

### ISSUE THREAD

**Issue by AlexHighTower** [atc1441/ATC_MiThermometer#44]
Hello,

I have two type of devices with inc screen:
- clear glass CGG1
- xiaomi MHO-C401

and I wonder if any work/progress/plans to have custom fw for this devices?

also can I activate/get token using web flash of this devices?

thanks

**Comment by m-kozlowski** [comment]
see #14 
and
https://github.com/znanev/MHO-C401

you can activate it, flash it and get measurements through BLE.
Screen does not work yet, but it seems it's just a matter of time.
