### ISSUE TITLE
Advertising type: 0xAE = Custom  0xAF = Mi Like <- Default

### ISSUE THREAD

**Issue by mihail4anov** [atc1441/ATC_MiThermometer#46]
Is is possible to make 
Advertising type: 
0xAE = Custom
0xAF = Mi Like **<- Default**
?

I am using the ESP and it is not comfortable to open a web page and connect to the device to change this parameter all the time after battery change.

**Comment by atc1441** [comment]
Please look at the other issues. I explained it before :)
