### ISSUE TITLE
Help with Sensor instant Advertising

### ISSUE THREAD

**Issue by nchieffo** [atc1441/ATC_MiThermometer#47]
I pushed the FC01 value to my device, but I can't see any difference when reading values from home assistant.
The value seems to update every 5 minutes even if there is 0.1° change in temperature
Can you help me?

**Comment by atc1441** [comment]
It is possible that the home assistant is only allows reading every 5 minutes. Maybe you can set it there

**Comment by nchieffo** [comment]
Hello and thanks for the reply

Actually the period is 60 seconds
This is the mod I'm using and the option:
https://github.com/custom-components/sensor.mitemp_bt#period

Is there any way to detect sensor advertising using Android app, just to see if the sensor is correctly advertising every 0.1°C?

**Comment by atc1441** [comment]
You can use nrfconnect app on android and will see the changing packet id(last byte) if the advertising is correct

**Comment by nchieffo** [comment]
Can you also suggest a command line util (also linux ok) to capture adv and read values (using Xiaomi like advertising)? With nrfconnect I have problems understanding how to use it, sorry

**Comment by atc1441** [comment]
I dont know any. Sorry.

With nrfconnect you can see how i use it in the video
