### ISSUE TITLE
What is the differences?

### ISSUE THREAD

**Issue by zuidwijk** [atc1441/ATC_MiThermometer#49]
Can you tell me what the differences are between these two screens?
![image](https://user-images.githubusercontent.com/10123063/96376507-8e3fd980-117f-11eb-8ba3-a8dc0184f5b8.jpeg)
![image](https://user-images.githubusercontent.com/10123063/96376514-9a2b9b80-117f-11eb-81c8-47fa79189c55.jpeg)
Both got the same temperature. The display without the smiley is/should be humidity. What is the other?

**Comment by atc1441** [comment]
Hey. The smiley itself is just blinking. 

The one with battery symbol is showing the battery in percent at the humidity data field. 

The one without is just humidity

**Comment by zuidwijk** [comment]
Thought so! Thank you for confirming :)
