### ISSUE TITLE
Strange fluctuating value since flashing the custom firmware

### ISSUE THREAD

**Issue by thestraycat** [atc1441/ATC_MiThermometer#57]
Hi! Love the project, congrats on your work.

Im using the small square 2020 version of the sensor and have successfully flashed it using the custom firmware and all steps have gone to plan as described by your tutorial. However now my humidity data keeps fluctuating between 68% and 96% every 5 seconds, it feels like a cached value is stuck somehow? Any idea what's happening here? After the flashing process i chose 'mi like' type and changed the interval to 5mins. Everything else is stock. Pics below to show the 2 screens that it cycles through.

![xiaomi2](https://user-images.githubusercontent.com/9296295/97258347-28eb8880-1810-11eb-9ffd-69cf661ba78f.jpg)
![xiaomi1](https://user-images.githubusercontent.com/9296295/97258349-29841f00-1810-11eb-841d-1a4d2ea8460b.jpg)

Why is it doing this?

**Comment by atc1441** [comment]
Hey. That is the battery status in percent. You see it when the battery icon is showing. You could also deactivate that if you want

**Comment by thestraycat** [comment]
Thanks for confirming, it wasn't clear to me! Cheers.
