### ISSUE TITLE
Difference between advertised value and display value

### ISSUE THREAD

**Issue by jcoetsie** [atc1441/ATC_MiThermometer#61]
After flashing a device to latest firmware, advertised value is different from display value.

When the smiley flashed, the humidity value goes to 97-99% and after smiley is gone it shows other value:

Practical case:

Temp:

Adv: 22.26°C
Display: 22.3°C

Hum:

Adv. 59%
Display no smiley: 57%
Display smiley: 97%

**Comment by atc1441** [comment]
Hey. 

That is because the battery status is schown in percent when the battery is shown. So your battery has 97% charge.

You can disable the function with the flasher if you want
