### ISSUE TITLE
Advertise temperature in F but ESPHome thinks it's C

### ISSUE THREAD

**Issue by joeandaverde** [atc1441/ATC_MiThermometer#62]
Changing the display output to F  seems to advertise in F but ESP home thinks that the value coming from the device is in C and converts. The temperature shown in Home Assistant is 150F.

**Comment by atc1441** [comment]
Yes. Changeing it to F does also change the advertising. 
It could be changed so it will only change the display to F

**Comment by joeandaverde** [comment]
Yeah, It seems like it should always send in C regardless of what it is displaying.

**Comment by joeandaverde** [comment]
atleast for esphome/homeassistant

**Comment by woody2010** [comment]
I came here to post the same issue, but I'm fairly new so perhaps its me not knowing I need to do something else.  Do I need to have HA convert the value if I want to have Fahrenheit used on the sensor?  My HA shows 154 degrees when I set the firmware to F.

**Comment by atc1441** [comment]
Just made an update so that only the LCD will be F and not all temp values

**Comment by woody2010** [comment]
Awesome! Thank you

**Comment by DiscoJeff** [comment]
You can also specify in ESPHome that the readings are in F

  - platform: xiaomi_lywsd03mmc
    mac_address: xxxxxxxxxxxxx
    bindkey: "xxxxxxxxxx"
    temperature:
      name: “Guest Bath Temperature"
      unit_of_measurement: "°F"
    humidity:
      name: "Guest Bath Humidity"
    battery_level:
      name: "Guest Bath Sensor Battery Level"

**Comment by atc1441** [comment]
Oh thank you for that info, will lea e it for now as it it but good to know

**Comment by BuxtonCalvin** [comment]
I hate to bring up this old topic but I'm hoping you can provide an easy fix for me.  My HA system does not allow underlying values to be converted --such as Celsius to Fahrenheit-- at the app level, only at a given created device level--devices sit on top of the app level data.  I use time series databases and other peripheral data repositories to store values that are pointed at the HA system, so I pull values from the app level.  

Would it be possible to add a UI flag that would allow one to specify whether they wanted the sent temp value to equal the UI value-- as currently, the sent value cannot be changed from Celsius.

Thx for the look.
