### ISSUE TITLE
Update error: NotSupportedError: GATT operation failed for unknown reason.

### ISSUE THREAD

**Issue by AndyCodeX** [atc1441/ATC_MiThermometer#69]
Error while flashing the stock firmware to go back. Too slow process (approx. 44 mins) and random time get this error. Applied stock firmware used: d4135e135443ba86e403ecb2af2bf0af_upd_miaomiaoce.sensor_ht.t2.zip - d4135e135443ba86e403ecb2af2bf0af_upd_miaomiaoce.sensor_ht.t2.bin for LYWSD03MMC. Unable to flash back to stock :(

**Comment by atc1441** [comment]
Try it a few times with reconnection it will get faster

**Comment by AndyCodeX** [comment]
I have found a solution: close all other opened tabs in a browser while flashing. Process took about 20s and successfully completed. Please add note about browser tabs to fleshing instruction.

**Comment by atc1441** [comment]
That should not be a problem, what is a problem is when you switch to another tab while flashing.

This is a chrome "feature" to save ram, it will only render the viewed tabs

**Comment by AndyCodeX** [comment]
> That should not be a problem, what is a problem is when you switch to another tab while flashing.
> 
> This is a chrome "feature" to save ram, it will only render the viewed tabs

I know about it but I didn't switch between tabs during flashing. It looks like Chrome shares processor time between tabs (processes) and it make flesher unresponsive from time to time. 
Just a guess...
