### ISSUE TITLE
Adjustable ADV-data buffer update period and smiley state parameter.

### ISSUE THREAD

**Issue by vevsvevs** [atc1441/ATC_MiThermometer#8]
1 minute is cool for most common use, but maybe it's a good idea to implement adjustability for this parameter via Bluetooth, the same way as it [was done](https://github.com/atc1441/ATC_MiThermometer/blob/master/ATC_Thermometer/ble.c#L77) for C/F setting? Also, it would be nice to have an adjustable parameter for smiley enabled/disabled/blink state ;)

**Comment by atc1441** [comment]
The smiley blinking enable/disable is planned. 

But the interval would not help much to change. It does not save power if its longer or shorter. So i dont think its to usefull. Or why do you think its good?

**Comment by vevsvevs** [comment]
Regarding smiley - I suggest implementing three states for it: permanently enabled, permanently disabled, and blink.

The interval changing goal is not a power consumption reduction (i got it from our previous conversation), but increase meaningful data obtaining frequency. In some circumstances, it's really handy to get actualized data every 10 secs.

**Comment by atc1441** [comment]
A setting for the smiley an Advertising interval was now added 
https://github.com/atc1441/ATC_MiThermometer#settings-in-custom-firmware
