### ISSUE TITLE
I cannot activate my device

### ISSUE THREAD

**Issue by onlize** [atc1441/ATC_MiThermometer#82]
Hello, I cannot activate my device. It tells me either:
23:03:11: Activating now, please wait...
23:03:12: Update error: some error while sending char data
23:03:12: Update error: some error while sending char data

Or:
23:03:19: Activating now, please wait...

Here is the picture:

![image](https://user-images.githubusercontent.com/28982031/99348964-69af4e00-2860-11eb-8f0a-ed89b0fc745a.png)

I try to make it work for a couple of hours now. I tried Google Chrome, Firefox, and Microsoft Edge. Can you help?

**Comment by atc1441** [comment]
Hey.

Could you also share the console log from chrome?
( at debug tools ) that could help to get further

**Comment by onlize** [comment]
Thank you for your reply. I am not sure if this is what you are looking for, but this is the only place for logs that I see:

![image](https://user-images.githubusercontent.com/28982031/99350253-85682380-2863-11eb-97a7-350347f61d88.png)

**Comment by atc1441** [comment]
Hey  that is not what meant but looks a bit strange. Try restarting both pc and device

**Comment by onlize** [comment]
Restarting everything helped. Thank you.
