### ISSUE TITLE
TypeError: device.watchAdvertisements is not a function

### ISSUE THREAD

**Issue by echopage** [atc1441/ATC_MiThermometer#85]
Hi, after flashing (via OTA) the custom firmware correctly, I tried to flash the original firmware, always without problems, only trying to flash the custom firmware again gives me this error: "TypeError: device.watchAdvertisements is not a function" after which it connects regularly, only that returning to the original firmware gives me sometimes strange characters on the Device id and no longer connects to MiHome

**Comment by hectaaaa** [comment]
I have a similar issue mine happened immediately after flashing custom firmware
